# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lush',
        ),
        migrations.RemoveField(
            model_name='serverlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
