# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20160325_0924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serverlist',
            table='serverlist',
        ),
    ]
