# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160325_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirft_size', models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], max_length=1)),
            ],
        ),
    ]
