# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
