# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20160329_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.ServerList')),
            ],
        ),
    ]
