#!/usr/bin/expect -f

set ip 192.168.0.70
set ip1 [lindex $argv 0]
set password Paic#234
set timeout 10
spawn ssh root@$ip
expect {
"*password:" { send "$password\r" }
}
expect "]*"
send "cd scripts\n"

if {$ip1 == "70"} {
    interact 
} elseif {$ip1 == "112"} {
    expect "]*"
    send "./70.exp\n"
    interact
} else {
    expect "]*"
    send "./70.exp\n"
    expect "]*"
    send "./70.exp $ip1\n"
    interact
}

